# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: duh.spec

# add or remove files that should be synced
files_to_sync:
    - duh.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: duh
# downstream (Fedora) RPM package name
downstream_package_name: duh

jobs:
    - job: copr_build
      trigger: pull_request
      targets:
        - fedora-all
