# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/alexsaezm/duh
%global goipath         github.com/alexsaezm/duh
Version:                1.0

%gometa

%global common_description %{expand:
Duh is a dummy Go library that I use for testing Fedora's package system.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           duh
Release:        1%{?dist}
Summary:        A dummy library

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Fri May 14 10:52:47 CEST 2021 Álex Sáez <alexsaezm@gmail.com> - 1.0-1
- Initial package

